#!/usr/bin/env python3
"""
scripts/render_certification_report.py

Renders a human-readable, machine-derived Markdown certification report from
evidence/<source_sha>/closure_result.json and closure_bundle.json.

Guarantees:
- Strictly derives all report claims from machine-verified evidence files.
- Rejects free-form manual editing of closure status.
- Includes complete cryptographic provenance (source SHA, invariant hash, toolchain).
"""

import argparse
import datetime
import json
import os
import sys

if hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))


def render_report(source_sha: str = "", result_path: str = "", output_path: str = "") -> str:
    # 1. Resolve source SHA and file paths
    if not source_sha:
        import subprocess
        try:
            res = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO_ROOT, capture_output=True, text=True)
            source_sha = res.stdout.strip()
        except Exception:
            source_sha = "UNKNOWN"

    ev_dir = os.path.join(REPO_ROOT, "evidence", source_sha)
    if not result_path:
        result_path = os.path.join(ev_dir, "closure_result.json")
    bundle_path = os.path.join(ev_dir, "closure_bundle.json")

    if not os.path.exists(result_path):
        print(f"[FAIL] Closure result file not found at: {result_path}")
        print("       Please run `python scripts/verify_closure_evidence.py` first.")
        sys.exit(1)

    with open(result_path, "r", encoding="utf-8") as f:
        result = json.load(f)

    bundle = {}
    if os.path.exists(bundle_path):
        with open(bundle_path, "r", encoding="utf-8") as f:
            bundle = json.load(f)

    si = bundle.get("source_identity", {})
    ci = bundle.get("contract_identity", {})
    tc = bundle.get("toolchain", {})
    te = bundle.get("test_execution", {})
    findings = result.get("findings", [])
    summary = result.get("summary", {})
    verdict = result.get("overall_verdict", "NOT_READY_FOR_CLOSURE")
    timestamp = result.get("timestamp", datetime.datetime.now(datetime.timezone.utc).isoformat())

    # Build Markdown Document
    md = []
    md.append(f"# Machine-Derived Production Certification Report")
    md.append(f"")
    md.append(f"> **Automated Evidence-Locked Certification Record**  ")
    md.append(f"> *This document is automatically generated by `scripts/render_certification_report.py` from verified machine evidence. Manual editing of closure verdicts or evidence results is strictly prohibited.*")
    md.append(f"")
    md.append(f"---")
    md.append(f"")

    # Overall Verdict Banner
    if verdict == "READY_FOR_CLOSURE":
        md.append(f"## 🟢 Machine Verdict: **READY FOR PRODUCTION CLOSURE**")
        md.append(f"All {summary.get('total_findings', 0)} architectural findings, invariant rules, and certification tests have been independently validated and verified with 0 failures.")
    else:
        md.append(f"## 🔴 Machine Verdict: **NOT READY FOR CLOSURE**")
        md.append(f"Remaining findings or invariant violations require resolution before production closure can be certified. ({summary.get('failed_findings', 0)} finding(s) failing).")
    md.append(f"")
    md.append(f"---")
    md.append(f"")

    # Provenance Table
    md.append(f"## 1. Cryptographic & Toolchain Provenance")
    md.append(f"")
    md.append(f"| Metric / Property | Value |")
    md.append(f"|---|---|")
    md.append(f"| **Source Git Commit SHA** | `{result.get('source_sha', source_sha)}` |")
    md.append(f"| **Git Branch** | `{si.get('git_branch', 'master')}` |")
    md.append(f"| **Working Tree Dirty** | `{si.get('is_dirty', False)}` |")
    md.append(f"| **Gradlew File Mode** | `{si.get('gradlew_git_mode', 'unknown')}` |")
    md.append(f"| **Authoritative Invariants SHA256** | `{ci.get('production_invariants_sha256', 'unknown')}` |")
    md.append(f"| **Evaluated Contract SHA256** | `{result.get('evaluated_contract_sha256', 'unknown')}` |")
    md.append(f"| **Operating System** | {tc.get('os', 'unknown')} |")
    md.append(f"| **Java Runtime** | {tc.get('java_version', 'unknown')} |")
    md.append(f"| **Gradle Version** | {tc.get('gradle_version', 'unknown')} |")
    md.append(f"| **Kotlin Compiler** | {tc.get('kotlin_version', 'unknown')} |")
    md.append(f"| **Evaluation Timestamp** | {timestamp} |")
    md.append(f"")
    md.append(f"---")
    md.append(f"")

    # Executive Summary Table
    md.append(f"## 2. Certification Executive Summary")
    md.append(f"")
    md.append(f"| Evaluation Dimension | Metric | Status |")
    md.append(f"|---|---|---|")
    md.append(f"| **Total Findings Evaluated** | {summary.get('total_findings', 0)} | INFO |")
    md.append(f"| **Passed Findings** | {summary.get('passed_findings', 0)} / {summary.get('total_findings', 0)} | {'✅ PASS' if summary.get('failed_findings', 0) == 0 else '❌ INCOMPLETE'} |")
    md.append(f"| **P0 Violations** | {summary.get('p0_failed', 0)} | {'✅ 0 P0' if summary.get('p0_failed', 0) == 0 else '❌ BLOCKING'} |")
    md.append(f"| **P1 Violations** | {summary.get('p1_failed', 0)} | {'✅ 0 P1' if summary.get('p1_failed', 0) == 0 else '❌ BLOCKING'} |")
    md.append(f"| **Total Unit/Integration Tests** | {te.get('total_tests', 0)} executed | {'✅ PASS' if te.get('failed_tests', 0) == 0 and te.get('error_tests', 0) == 0 and te.get('total_tests', 0) > 0 else '❌ FAIL'} |")
    md.append(f"| **Test Failures / Errors** | {te.get('failed_tests', 0)} failures, {te.get('error_tests', 0)} errors | {'✅ 0 Failures' if te.get('failed_tests', 0) == 0 and te.get('error_tests', 0) == 0 else '❌ DEFECT'} |")
    md.append(f"| **Test Skips** | {te.get('skipped_tests', 0)} skipped | {'✅ 0 Skips' if te.get('skipped_tests', 0) == 0 else '⚠️ SKIPPED'} |")
    md.append(f"| **Test Suite Duration** | {te.get('duration_seconds', 0)} s | INFO |")
    md.append(f"")
    md.append(f"---")
    md.append(f"")

    # Findings Status Matrix
    md.append(f"## 3. Finding-by-Finding Closure Status Matrix")
    md.append(f"")
    md.append(f"| Finding ID | Invariant | Severity | Structural Proof | Behavioral Proof | Artifacts | Derived Verdict |")
    md.append(f"|---|---|---|---|---|---|---|")
    for f in findings:
        f_id = f.get("id")
        f_inv = f.get("invariant")
        f_sev = f.get("severity")
        st_s = "✅ PASS" if f.get("structural_status") == "PASS" else "❌ FAIL"
        be_s = "✅ PASS" if f.get("behavioral_status") == "PASS" else "❌ FAIL"
        ar_s = "✅ PASS" if f.get("artifact_status") == "PASS" else "❌ FAIL"
        de_s = "**✅ CLOSED**" if f.get("derived_status") == "PASS" else "**❌ OPEN**"
        md.append(f"| `{f_id}` | `{f_inv}` | `{f_sev}` | {st_s} | {be_s} | {ar_s} | {de_s} |")
    md.append(f"")
    md.append(f"---")
    md.append(f"")

    # Detailed Findings Proof
    md.append(f"## 4. Evidence Verification Details per Finding")
    md.append(f"")
    for f in findings:
        f_id = f.get("id")
        f_title = f.get("title")
        f_inv = f.get("invariant")
        f_sev = f.get("severity")
        f_status = f.get("derived_status")
        f_reasons = f.get("failed_reasons", [])
        c_sum = f.get("checks_summary", {})

        badge = "✅ PASS" if f_status == "PASS" else "❌ FAIL"
        md.append(f"### Finding `{f_id}`: {f_title} ({badge})")
        md.append(f"- **Invariant:** `{f_inv}` | **Severity:** `{f_sev}` | **Derived Verdict:** `{f_status}`")
        md.append(f"- **Required Structural Checks:** {', '.join([f'`{x}`' for x in c_sum.get('required_structural', [])]) or 'None'}")
        md.append(f"- **Required Behavioral Tests:** {', '.join([f'`{x}`' for x in c_sum.get('required_behavioral', [])]) or 'None'}")
        md.append(f"- **Source Paths:** {', '.join([f'`{x}`' for x in c_sum.get('source_paths', [])]) or 'None'}")
        if f_reasons:
            md.append(f"- **Failure Details:**")
            for r in f_reasons:
                md.append(f"  * ❌ {r}")
        md.append(f"")

    md.append(f"---")
    md.append(f"")

    # Structural Checks Detailed Results
    md.append(f"## 5. Structural & Static Guard Summary")
    md.append(f"")
    md.append(f"| Check Name | Status | Details |")
    md.append(f"|---|---|---|")
    sc_dict = bundle.get("structural_checks", {})
    for sc_name, sc_val in sc_dict.items():
        status_badge = "✅ PASS" if sc_val.get("status") == "PASS" else "❌ FAIL"
        details_txt = str(sc_val.get("details", "")).replace("\n", " ")
        if len(details_txt) > 80:
            details_txt = details_txt[:77] + "..."
        md.append(f"| `{sc_name}` | {status_badge} | {details_txt} |")
    md.append(f"")
    md.append(f"---")
    md.append(f"")

    # Test Execution Suite Breakdown
    md.append(f"## 6. Test Suite Execution Breakdown")
    md.append(f"")
    md.append(f"| Test Suite Name | Total Tests | Failures | Errors | Skipped | Time (s) | Status |")
    md.append(f"|---|---|---|---|---|---|---|")
    suites = te.get("suites", [])
    for s in suites:
        s_name = s.get("name", "").replace("com.example.", "")
        s_total = s.get("tests", 0)
        s_fail = s.get("failures", 0)
        s_err = s.get("errors", 0)
        s_skip = s.get("skipped", 0)
        s_time = s.get("time", 0.0)
        s_status = "✅ PASS" if (s_fail == 0 and s_err == 0) else "❌ FAIL"
        md.append(f"| `{s_name}` | {s_total} | {s_fail} | {s_err} | {s_skip} | {s_time:.3f} | {s_status} |")

    md.append(f"")
    md.append(f"---")
    md.append(f"")
    md.append(f"**Report Generated Automatically by Earthlink Reseller CI/CD Evidence Engine.**")

    full_report_text = "\n".join(md) + "\n"

    # Write report
    if not output_path:
        output_path = os.path.join(ev_dir, "CERTIFICATION_REPORT.md")
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(full_report_text)

    print("=================================================================")
    print("=== Certification Report Rendered ===")
    print(f"Report File : {os.path.relpath(output_path, REPO_ROOT)}")
    print(f"Verdict     : {verdict}")
    print("=================================================================")
    return full_report_text


def main():
    parser = argparse.ArgumentParser(description="Render Earthlink Certification Report")
    parser.add_argument("--source-sha", default="", help="Git SHA of source commit")
    parser.add_argument("--result", default="", help="Path to closure_result.json")
    parser.add_argument("--output", default="", help="Path for output Markdown report")
    args = parser.parse_args()

    render_report(source_sha=args.source_sha, result_path=args.result, output_path=args.output)


if __name__ == "__main__":
    main()
